name: triangles_background
description: Animated triangles background widget with color gradients
version: 1.0.1
author: Marco Bavagnoli
homepage: https://github.com/alnitak/flutter_triangles_background
repository: https://github.com/alnitak/flutter_triangles_background

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
